apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
#  namespace: "{{ .Values.namespace }}"
data:
  pg-host: "{{ .Values.database.postgres.host }}"
  pg-port: "{{ .Values.database.postgres.port }}"
  pg-user: "{{ .Values.database.postgres.user }}"
  pg-name: "{{ .Values.database.postgres.database }}"
  pg-schema: "users"
#  app-port: "8000"
