apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: user-secrets
  namespace: {{ .Values.namespace }}
  labels:
    name: user-secrets
data:
  pg-password: {{ printf .Values.database.postgres.password | b64enc | quote }}
