apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-ingress
  namespace: "{{ .Values.namespace }}"
  annotations:
    meta.helm.sh: "{{ .Chart.Name }}"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
        rewrite ^/health/?$ /health break;
        rewrite ^/otusapp/([A-Za-z]+)/.* / break;
        return 500;
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: user-service
                port:
                  number: 80
            pathType: Prefix
            path: /


