replicaCount: 1
namespace: "otus"

image:
  repository: irmdevdocker/user
  pullPolicy: IfNotPresent
  tag: 0.0.2

ingress:
  enabled: true
  className: "nginx"
  namespace: ${namespace}
  host: arch.homework


database:
  postgres:
    replicaCount: 1
    host: "chart-user-postgresql"
    database: "otus"
    password: "test123"
    user: "postgres"
    port: "5432"
    namespace: ${namespace}

global:
  postgresql:
    namespace: ${namespace}
    auth:
      username: "postgres"
      password: "test123"
      database: "otus"
      postgresPassword: "test123"