replicaCount: 1
namespace: "m"

image:
  repository: irmdevdocker/user
  pullPolicy: IfNotPresent
  tag: 0.0.1

ingress:
  enabled: true
  className: "nginx"
  namespace: ${namespace}
  host: arch.homework


database:
  postgres:
    replicaCount: 1
    host: "user-db-postgresql"
    database: "otus"
    password: "test123"
    user: "postgres"
    port: "5432"
    namespace: ${namespace}

